// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ONFTComposeMsgCodec$Type } from "./ONFTComposeMsgCodec";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ONFTComposeMsgCodec"]: ONFTComposeMsgCodec$Type;
    ["contracts/onft721/libs/ONFTComposeMsgCodec.sol:ONFTComposeMsgCodec"]: ONFTComposeMsgCodec$Type;
  }

  interface ContractTypesMap {
    ["ONFTComposeMsgCodec"]: GetContractReturnType<ONFTComposeMsgCodec$Type["abi"]>;
    ["contracts/onft721/libs/ONFTComposeMsgCodec.sol:ONFTComposeMsgCodec"]: GetContractReturnType<ONFTComposeMsgCodec$Type["abi"]>;
  }
}
