// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ONFTComposeMsgCodec$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ONFTComposeMsgCodec",
  "sourceName": "contracts/onft721/libs/ONFTComposeMsgCodec.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f1bd1e8979d8a5f47820dfd6f51947ab3079a01fd9c93428eb847f264837db0364736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f1bd1e8979d8a5f47820dfd6f51947ab3079a01fd9c93428eb847f264837db0364736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ONFTComposeMsgCodec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ONFTComposeMsgCodec$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/onft721/libs/ONFTComposeMsgCodec.sol:ONFTComposeMsgCodec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ONFTComposeMsgCodec$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ONFTComposeMsgCodec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ONFTComposeMsgCodec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/onft721/libs/ONFTComposeMsgCodec.sol:ONFTComposeMsgCodec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ONFTComposeMsgCodec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ONFTComposeMsgCodec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ONFTComposeMsgCodec$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/onft721/libs/ONFTComposeMsgCodec.sol:ONFTComposeMsgCodec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ONFTComposeMsgCodec$Type["abi"]>>;
}
