// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IMessagingComposer$Type } from "./IMessagingComposer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMessagingComposer"]: IMessagingComposer$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessagingComposer.sol:IMessagingComposer"]: IMessagingComposer$Type;
  }

  interface ContractTypesMap {
    ["IMessagingComposer"]: GetContractReturnType<IMessagingComposer$Type["abi"]>;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessagingComposer.sol:IMessagingComposer"]: GetContractReturnType<IMessagingComposer$Type["abi"]>;
  }
}
