// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PoolSrcFactory$Type } from "./PoolSrcFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PoolSrcFactory"]: PoolSrcFactory$Type;
    ["contracts/PoolSrcFactory.sol:PoolSrcFactory"]: PoolSrcFactory$Type;
  }

  interface ContractTypesMap {
    ["PoolSrcFactory"]: GetContractReturnType<PoolSrcFactory$Type["abi"]>;
    ["contracts/PoolSrcFactory.sol:PoolSrcFactory"]: GetContractReturnType<PoolSrcFactory$Type["abi"]>;
  }
}
