// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ONFT721Core$Type } from "./ONFT721Core";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ONFT721Core"]: ONFT721Core$Type;
    ["contracts/onft721/ONFT721Core.sol:ONFT721Core"]: ONFT721Core$Type;
  }

  interface ContractTypesMap {
    ["ONFT721Core"]: GetContractReturnType<ONFT721Core$Type["abi"]>;
    ["contracts/onft721/ONFT721Core.sol:ONFT721Core"]: GetContractReturnType<ONFT721Core$Type["abi"]>;
  }
}
