// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ILayerZeroEndpointV2$Type } from "./ILayerZeroEndpointV2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ILayerZeroEndpointV2"]: ILayerZeroEndpointV2$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/ILayerZeroEndpointV2.sol:ILayerZeroEndpointV2"]: ILayerZeroEndpointV2$Type;
  }

  interface ContractTypesMap {
    ["ILayerZeroEndpointV2"]: GetContractReturnType<ILayerZeroEndpointV2$Type["abi"]>;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/ILayerZeroEndpointV2.sol:ILayerZeroEndpointV2"]: GetContractReturnType<ILayerZeroEndpointV2$Type["abi"]>;
  }
}
