// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PacketDecoder$Type } from "./PacketDecoder";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PacketDecoder"]: PacketDecoder$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/precrime/libs/Packet.sol:PacketDecoder"]: PacketDecoder$Type;
  }

  interface ContractTypesMap {
    ["PacketDecoder"]: GetContractReturnType<PacketDecoder$Type["abi"]>;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/precrime/libs/Packet.sol:PacketDecoder"]: GetContractReturnType<PacketDecoder$Type["abi"]>;
  }
}
