// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IOracle$Type } from "./IOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IOracle"]: IOracle$Type;
    ["contracts/interfaces/oracles/IOracle.sol:IOracle"]: IOracle$Type;
  }

  interface ContractTypesMap {
    ["IOracle"]: GetContractReturnType<IOracle$Type["abi"]>;
    ["contracts/interfaces/oracles/IOracle.sol:IOracle"]: GetContractReturnType<IOracle$Type["abi"]>;
  }
}
