// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISendLib$Type } from "./ISendLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISendLib"]: ISendLib$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/ISendLib.sol:ISendLib"]: ISendLib$Type;
  }

  interface ContractTypesMap {
    ["ISendLib"]: GetContractReturnType<ISendLib$Type["abi"]>;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/ISendLib.sol:ISendLib"]: GetContractReturnType<ISendLib$Type["abi"]>;
  }
}
