// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SrcPool$Type } from "./SrcPool";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SrcPool"]: SrcPool$Type;
    ["contracts/SrcPool.sol:SrcPool"]: SrcPool$Type;
  }

  interface ContractTypesMap {
    ["SrcPool"]: GetContractReturnType<SrcPool$Type["abi"]>;
    ["contracts/SrcPool.sol:SrcPool"]: GetContractReturnType<SrcPool$Type["abi"]>;
  }
}
