// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IONFT721$Type } from "./IONFT721";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IONFT721"]: IONFT721$Type;
    ["contracts/onft721/interfaces/IONFT721.sol:IONFT721"]: IONFT721$Type;
  }

  interface ContractTypesMap {
    ["IONFT721"]: GetContractReturnType<IONFT721$Type["abi"]>;
    ["contracts/onft721/interfaces/IONFT721.sol:IONFT721"]: GetContractReturnType<IONFT721$Type["abi"]>;
  }
}
