// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDstPool$Type } from "./IDstPool";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDstPool"]: IDstPool$Type;
    ["contracts/interfaces/IDstPool.sol:IDstPool"]: IDstPool$Type;
  }

  interface ContractTypesMap {
    ["IDstPool"]: GetContractReturnType<IDstPool$Type["abi"]>;
    ["contracts/interfaces/IDstPool.sol:IDstPool"]: GetContractReturnType<IDstPool$Type["abi"]>;
  }
}
