// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IOAppReceiver$Type } from "./IOAppReceiver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IOAppReceiver"]: IOAppReceiver$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/interfaces/IOAppReceiver.sol:IOAppReceiver"]: IOAppReceiver$Type;
  }

  interface ContractTypesMap {
    ["IOAppReceiver"]: GetContractReturnType<IOAppReceiver$Type["abi"]>;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/interfaces/IOAppReceiver.sol:IOAppReceiver"]: GetContractReturnType<IOAppReceiver$Type["abi"]>;
  }
}
