// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPyth$Type } from "./IPyth";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPyth"]: IPyth$Type;
    ["@pythnetwork/pyth-sdk-solidity/IPyth.sol:IPyth"]: IPyth$Type;
  }

  interface ContractTypesMap {
    ["IPyth"]: GetContractReturnType<IPyth$Type["abi"]>;
    ["@pythnetwork/pyth-sdk-solidity/IPyth.sol:IPyth"]: GetContractReturnType<IPyth$Type["abi"]>;
  }
}
