// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISelfKisser$Type } from "./ISelfKisser";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISelfKisser"]: ISelfKisser$Type;
    ["contracts/interfaces/oracles/ISelfKisser.sol:ISelfKisser"]: ISelfKisser$Type;
  }

  interface ContractTypesMap {
    ["ISelfKisser"]: GetContractReturnType<ISelfKisser$Type["abi"]>;
    ["contracts/interfaces/oracles/ISelfKisser.sol:ISelfKisser"]: GetContractReturnType<ISelfKisser$Type["abi"]>;
  }
}
