// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { OAppSender$Type } from "./OAppSender";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OAppSender"]: OAppSender$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppSender.sol:OAppSender"]: OAppSender$Type;
  }

  interface ContractTypesMap {
    ["OAppSender"]: GetContractReturnType<OAppSender$Type["abi"]>;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppSender.sol:OAppSender"]: GetContractReturnType<OAppSender$Type["abi"]>;
  }
}
