// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ONFT721Adapter$Type } from "./ONFT721Adapter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ONFT721Adapter"]: ONFT721Adapter$Type;
    ["contracts/onft721/ONFT721Adapter.sol:ONFT721Adapter"]: ONFT721Adapter$Type;
  }

  interface ContractTypesMap {
    ["ONFT721Adapter"]: GetContractReturnType<ONFT721Adapter$Type["abi"]>;
    ["contracts/onft721/ONFT721Adapter.sol:ONFT721Adapter"]: GetContractReturnType<ONFT721Adapter$Type["abi"]>;
  }
}
