// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PythStructs$Type } from "./PythStructs";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PythStructs"]: PythStructs$Type;
    ["@pythnetwork/pyth-sdk-solidity/PythStructs.sol:PythStructs"]: PythStructs$Type;
  }

  interface ContractTypesMap {
    ["PythStructs"]: GetContractReturnType<PythStructs$Type["abi"]>;
    ["@pythnetwork/pyth-sdk-solidity/PythStructs.sol:PythStructs"]: GetContractReturnType<PythStructs$Type["abi"]>;
  }
}
