// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface PythStructs$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "PythStructs",
  "sourceName": "@pythnetwork/pyth-sdk-solidity/PythStructs.sol",
  "abi": [],
  "bytecode": "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212201b8035188fee65bb2aeaa17116093598c545c80b5f3775791d2862ead728967564736f6c63430008180033",
  "deployedBytecode": "0x6080604052600080fdfea26469706673582212201b8035188fee65bb2aeaa17116093598c545c80b5f3775791d2862ead728967564736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "PythStructs",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<PythStructs$Type["abi"]>>;
  export function deployContract(
    contractName: "@pythnetwork/pyth-sdk-solidity/PythStructs.sol:PythStructs",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<PythStructs$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "PythStructs",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<PythStructs$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@pythnetwork/pyth-sdk-solidity/PythStructs.sol:PythStructs",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<PythStructs$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "PythStructs",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<PythStructs$Type["abi"]>>;
  export function getContractAt(
    contractName: "@pythnetwork/pyth-sdk-solidity/PythStructs.sol:PythStructs",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<PythStructs$Type["abi"]>>;
}
