// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Oracle$Type } from "./Oracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Oracle"]: Oracle$Type;
    ["contracts/Oracle.sol:Oracle"]: Oracle$Type;
  }

  interface ContractTypesMap {
    ["Oracle"]: GetContractReturnType<Oracle$Type["abi"]>;
    ["contracts/Oracle.sol:Oracle"]: GetContractReturnType<Oracle$Type["abi"]>;
  }
}
