// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IMessagingChannel$Type } from "./IMessagingChannel";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMessagingChannel"]: IMessagingChannel$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessagingChannel.sol:IMessagingChannel"]: IMessagingChannel$Type;
  }

  interface ContractTypesMap {
    ["IMessagingChannel"]: GetContractReturnType<IMessagingChannel$Type["abi"]>;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessagingChannel.sol:IMessagingChannel"]: GetContractReturnType<IMessagingChannel$Type["abi"]>;
  }
}
