// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ILayerZeroReceiver$Type } from "./ILayerZeroReceiver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ILayerZeroReceiver"]: ILayerZeroReceiver$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/ILayerZeroReceiver.sol:ILayerZeroReceiver"]: ILayerZeroReceiver$Type;
  }

  interface ContractTypesMap {
    ["ILayerZeroReceiver"]: GetContractReturnType<ILayerZeroReceiver$Type["abi"]>;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/ILayerZeroReceiver.sol:ILayerZeroReceiver"]: GetContractReturnType<ILayerZeroReceiver$Type["abi"]>;
  }
}
