// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PoolDstFactory$Type } from "./PoolDstFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PoolDstFactory"]: PoolDstFactory$Type;
    ["contracts/PoolDstFactory.sol:PoolDstFactory"]: PoolDstFactory$Type;
  }

  interface ContractTypesMap {
    ["PoolDstFactory"]: GetContractReturnType<PoolDstFactory$Type["abi"]>;
    ["contracts/PoolDstFactory.sol:PoolDstFactory"]: GetContractReturnType<PoolDstFactory$Type["abi"]>;
  }
}
