// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { FlareOracle$Type } from "./FlareOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FlareOracle"]: FlareOracle$Type;
    ["contracts/oracles/FlareOracle.sol:FlareOracle"]: FlareOracle$Type;
  }

  interface ContractTypesMap {
    ["FlareOracle"]: GetContractReturnType<FlareOracle$Type["abi"]>;
    ["contracts/oracles/FlareOracle.sol:FlareOracle"]: GetContractReturnType<FlareOracle$Type["abi"]>;
  }
}
