// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PythOracle$Type } from "./PythOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PythOracle"]: PythOracle$Type;
    ["contracts/oracles/PythOracle.sol:PythOracle"]: PythOracle$Type;
  }

  interface ContractTypesMap {
    ["PythOracle"]: GetContractReturnType<PythOracle$Type["abi"]>;
    ["contracts/oracles/PythOracle.sol:PythOracle"]: GetContractReturnType<PythOracle$Type["abi"]>;
  }
}
