// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISrcPool$Type } from "./ISrcPool";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISrcPool"]: ISrcPool$Type;
    ["contracts/interfaces/ISrcPool.sol:ISrcPool"]: ISrcPool$Type;
  }

  interface ContractTypesMap {
    ["ISrcPool"]: GetContractReturnType<ISrcPool$Type["abi"]>;
    ["contracts/interfaces/ISrcPool.sol:ISrcPool"]: GetContractReturnType<ISrcPool$Type["abi"]>;
  }
}
