// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BatchSend$Type } from "./BatchSend";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BatchSend"]: BatchSend$Type;
    ["contracts/tests/BatchSend.sol:BatchSend"]: BatchSend$Type;
  }

  interface ContractTypesMap {
    ["BatchSend"]: GetContractReturnType<BatchSend$Type["abi"]>;
    ["contracts/tests/BatchSend.sol:BatchSend"]: GetContractReturnType<BatchSend$Type["abi"]>;
  }
}
