// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ONFT721$Type } from "./ONFT721";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ONFT721"]: ONFT721$Type;
    ["contracts/onft721/ONFT721.sol:ONFT721"]: ONFT721$Type;
  }

  interface ContractTypesMap {
    ["ONFT721"]: GetContractReturnType<ONFT721$Type["abi"]>;
    ["contracts/onft721/ONFT721.sol:ONFT721"]: GetContractReturnType<ONFT721$Type["abi"]>;
  }
}
