// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IChronicle$Type } from "./IChronicle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IChronicle"]: IChronicle$Type;
    ["contracts/interfaces/oracles/IChronicle.sol:IChronicle"]: IChronicle$Type;
  }

  interface ContractTypesMap {
    ["IChronicle"]: GetContractReturnType<IChronicle$Type["abi"]>;
    ["contracts/interfaces/oracles/IChronicle.sol:IChronicle"]: GetContractReturnType<IChronicle$Type["abi"]>;
  }
}
