// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IMessageLibManager$Type } from "./IMessageLibManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMessageLibManager"]: IMessageLibManager$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessageLibManager.sol:IMessageLibManager"]: IMessageLibManager$Type;
  }

  interface ContractTypesMap {
    ["IMessageLibManager"]: GetContractReturnType<IMessageLibManager$Type["abi"]>;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessageLibManager.sol:IMessageLibManager"]: GetContractReturnType<IMessageLibManager$Type["abi"]>;
  }
}
