// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ONFT721MsgCodec$Type } from "./ONFT721MsgCodec";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ONFT721MsgCodec"]: ONFT721MsgCodec$Type;
    ["contracts/onft721/libs/ONFT721MsgCodec.sol:ONFT721MsgCodec"]: ONFT721MsgCodec$Type;
  }

  interface ContractTypesMap {
    ["ONFT721MsgCodec"]: GetContractReturnType<ONFT721MsgCodec$Type["abi"]>;
    ["contracts/onft721/libs/ONFT721MsgCodec.sol:ONFT721MsgCodec"]: GetContractReturnType<ONFT721MsgCodec$Type["abi"]>;
  }
}
