// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ONFT721MsgCodec$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ONFT721MsgCodec",
  "sourceName": "contracts/onft721/libs/ONFT721MsgCodec.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212203426d6e2564d82480c15e85d7bf6cc23ad716d1fc122a27a97b56bfe97c5279264736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212203426d6e2564d82480c15e85d7bf6cc23ad716d1fc122a27a97b56bfe97c5279264736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ONFT721MsgCodec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ONFT721MsgCodec$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/onft721/libs/ONFT721MsgCodec.sol:ONFT721MsgCodec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ONFT721MsgCodec$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ONFT721MsgCodec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ONFT721MsgCodec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/onft721/libs/ONFT721MsgCodec.sol:ONFT721MsgCodec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ONFT721MsgCodec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ONFT721MsgCodec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ONFT721MsgCodec$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/onft721/libs/ONFT721MsgCodec.sol:ONFT721MsgCodec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ONFT721MsgCodec$Type["abi"]>>;
}
