// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPythEvents$Type } from "./IPythEvents";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPythEvents"]: IPythEvents$Type;
    ["@pythnetwork/pyth-sdk-solidity/IPythEvents.sol:IPythEvents"]: IPythEvents$Type;
  }

  interface ContractTypesMap {
    ["IPythEvents"]: GetContractReturnType<IPythEvents$Type["abi"]>;
    ["@pythnetwork/pyth-sdk-solidity/IPythEvents.sol:IPythEvents"]: GetContractReturnType<IPythEvents$Type["abi"]>;
  }
}
