// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IPythEvents$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IPythEvents",
  "sourceName": "@pythnetwork/pyth-sdk-solidity/IPythEvents.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "id",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint64",
          "name": "publishTime",
          "type": "uint64"
        },
        {
          "indexed": false,
          "internalType": "int64",
          "name": "price",
          "type": "int64"
        },
        {
          "indexed": false,
          "internalType": "uint64",
          "name": "conf",
          "type": "uint64"
        }
      ],
      "name": "PriceFeedUpdate",
      "type": "event"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IPythEvents",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IPythEvents$Type["abi"]>>;
  export function deployContract(
    contractName: "@pythnetwork/pyth-sdk-solidity/IPythEvents.sol:IPythEvents",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IPythEvents$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IPythEvents",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IPythEvents$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@pythnetwork/pyth-sdk-solidity/IPythEvents.sol:IPythEvents",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IPythEvents$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IPythEvents",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IPythEvents$Type["abi"]>>;
  export function getContractAt(
    contractName: "@pythnetwork/pyth-sdk-solidity/IPythEvents.sol:IPythEvents",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IPythEvents$Type["abi"]>>;
}
