// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { OAppOptionsType3$Type } from "./OAppOptionsType3";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OAppOptionsType3"]: OAppOptionsType3$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/libs/OAppOptionsType3.sol:OAppOptionsType3"]: OAppOptionsType3$Type;
  }

  interface ContractTypesMap {
    ["OAppOptionsType3"]: GetContractReturnType<OAppOptionsType3$Type["abi"]>;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/libs/OAppOptionsType3.sol:OAppOptionsType3"]: GetContractReturnType<OAppOptionsType3$Type["abi"]>;
  }
}
