// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IOAppMsgInspector$Type } from "./IOAppMsgInspector";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IOAppMsgInspector"]: IOAppMsgInspector$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/interfaces/IOAppMsgInspector.sol:IOAppMsgInspector"]: IOAppMsgInspector$Type;
  }

  interface ContractTypesMap {
    ["IOAppMsgInspector"]: GetContractReturnType<IOAppMsgInspector$Type["abi"]>;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/interfaces/IOAppMsgInspector.sol:IOAppMsgInspector"]: GetContractReturnType<IOAppMsgInspector$Type["abi"]>;
  }
}
