// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ChronicleOracle$Type } from "./ChronicleOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ChronicleOracle"]: ChronicleOracle$Type;
    ["contracts/oracles/ChronicleOracle.sol:ChronicleOracle"]: ChronicleOracle$Type;
  }

  interface ContractTypesMap {
    ["ChronicleOracle"]: GetContractReturnType<ChronicleOracle$Type["abi"]>;
    ["contracts/oracles/ChronicleOracle.sol:ChronicleOracle"]: GetContractReturnType<ChronicleOracle$Type["abi"]>;
  }
}
