// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { OAppCore$Type } from "./OAppCore";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OAppCore"]: OAppCore$Type;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppCore.sol:OAppCore"]: OAppCore$Type;
  }

  interface ContractTypesMap {
    ["OAppCore"]: GetContractReturnType<OAppCore$Type["abi"]>;
    ["@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppCore.sol:OAppCore"]: GetContractReturnType<OAppCore$Type["abi"]>;
  }
}
