// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PacketV1Codec$Type } from "./PacketV1Codec";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PacketV1Codec"]: PacketV1Codec$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/messagelib/libs/PacketV1Codec.sol:PacketV1Codec"]: PacketV1Codec$Type;
  }

  interface ContractTypesMap {
    ["PacketV1Codec"]: GetContractReturnType<PacketV1Codec$Type["abi"]>;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/messagelib/libs/PacketV1Codec.sol:PacketV1Codec"]: GetContractReturnType<PacketV1Codec$Type["abi"]>;
  }
}
