// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AddressCast$Type } from "./AddressCast";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AddressCast"]: AddressCast$Type;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/libs/AddressCast.sol:AddressCast"]: AddressCast$Type;
  }

  interface ContractTypesMap {
    ["AddressCast"]: GetContractReturnType<AddressCast$Type["abi"]>;
    ["@layerzerolabs/lz-evm-protocol-v2/contracts/libs/AddressCast.sol:AddressCast"]: GetContractReturnType<AddressCast$Type["abi"]>;
  }
}
